### ISSUE TITLE
BLE MIDI service not advertising

### ISSUE THREAD

**Issue by bduhan** [neilbags/arduino-esp32-BLE-MIDI#7]
The example BLE MIDI service was not being advertised so iOS apps such as GarageBand and midimittr could not find my device.

Fixed in pull request #6

**Comment by neilbags** [comment]
Merged in commit https://github.com/neilbags/arduino-esp32-BLE-MIDI/commit/4692324f8d0672fc49c50ffaf6f2d59ec0d79a42
Thanks for your contribution
